// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuOaGRnlyto1agvFXm2jF-ozdBIEaggUo',
    appId: '1:594620927040:web:355ad2a480aa8992f223a5',
    messagingSenderId: '594620927040',
    projectId: 'regali-dxme',
    authDomain: 'regali-dxme.firebaseapp.com',
    storageBucket: 'regali-dxme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8GTfc2AhCYNpDtlNuU9pCwk0FyB2R9k',
    appId: '1:594620927040:android:21cba13285cc8e53f223a5',
    messagingSenderId: '594620927040',
    projectId: 'regali-dxme',
    storageBucket: 'regali-dxme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQf26h22myj9MObUCZHQfy71mkK4-99mM',
    appId: '1:594620927040:ios:dd21b5fa3615a364f223a5',
    messagingSenderId: '594620927040',
    projectId: 'regali-dxme',
    storageBucket: 'regali-dxme.firebasestorage.app',
    iosBundleId: 'com.example.regali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQf26h22myj9MObUCZHQfy71mkK4-99mM',
    appId: '1:594620927040:ios:dd21b5fa3615a364f223a5',
    messagingSenderId: '594620927040',
    projectId: 'regali-dxme',
    storageBucket: 'regali-dxme.firebasestorage.app',
    iosBundleId: 'com.example.regali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuOaGRnlyto1agvFXm2jF-ozdBIEaggUo',
    appId: '1:594620927040:web:747ed1023ed182b8f223a5',
    messagingSenderId: '594620927040',
    projectId: 'regali-dxme',
    authDomain: 'regali-dxme.firebaseapp.com',
    storageBucket: 'regali-dxme.firebasestorage.app',
  );
}
